name: BuguTV自动签到

on:
  schedule:
    - cron: '0 0 * * *' # 每天UTC时间0点，即北京时间早上8点运行
  workflow_dispatch: # 支持手动触发

jobs:
  auto_sign:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: 缓存Python依赖
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 创建环境变量文件
      run: |
        echo "BUGUTV_USERNAME=${{ secrets.BUGUTV_USERNAME }}" >> .env
        echo "BUGUTV_PASSWORD=${{ secrets.BUGUTV_PASSWORD }}" >> .env
        echo "EMAIL_HOST=${{ secrets.EMAIL_HOST }}" >> .env
        echo "EMAIL_PORT=${{ secrets.EMAIL_PORT }}" >> .env
        echo "EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}" >> .env
        echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
        echo "EMAIL_TO=${{ secrets.EMAIL_TO }}" >> .env
        
    - name: 运行签到脚本
      run: python autosign.py
      
    - name: 上传日志
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: logs/ 
